config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'

  get 'posts', to: 'posts#index'

  get 'users/new', to: 'users#new'

  post 'users', to: 'users#create'

  post 'posts', to: 'posts#create'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :image, styles: { thumb: "250x250>"}, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @user = User.last
    @post = Post.new
  end

  def create
    @post = Post.create(params.require(:post).permit(:content))
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @new_user = User.new
    @user = User.last
  end

  def create
    @user = User.create(user_params)
    if @user.persisted?
      redirect_to root_path
    else
      render :new
    end
  end

private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeBook</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav navbar bg-primary" style="padding:20px">
      <%= link_to "MeBook", root_path, :style => "color: white; font-size: 50px" %>
      <div class="navbar-right">
        <div class="navbar-text" style="font-size: 20px">Welcome, <%= @user.first_name %></div>
        <%= link_to (image_tag @user.image, :width => "120px"), users_new_path %>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Welcome to MeBook!</h1>
<br><br>

  <div class="row">
  <%= form_for @post do |form| %>
    <%= form.text_field :content, placeholder: "What's on your mind...", :style => "line-height: 40px", :size => "80px" %>
    <br><br>
    <%= form.submit "Post" %>
  <% end %>
  </div>
  <br>
  <hr>
  <div class="conatiner">
  <h2>Your Posts</h2>
  </div>
  <br>
<div class="panel-group">
  <% @posts.reverse.each do |post| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <strong class="col-xs-10"><%= post.content %></strong>
      <small class="col-xs-2"><%= post.created_at.strftime("%B %d, %Y") %></small>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Add or update user profile data!</h1>

<%= form_for @new_user, html: {multipart: true} do |form| %>
  <%= form.text_field :first_name %><br>
  <%= form.label :first_name %><br><br>

  <%= form.text_field :last_name %><br>
  <%= form.label :last_name %><br><br>

  <%= form.file_field :image %>
  <strong>Profile Picture </strong><br><br>

  <%= form.submit "Done" %>
<% end %>